# Run: sourcekitten doc --spm-module BitByteData > docs.json
sourcekitten_sourcefile: docs.json
clean: true
author: Timofey Solomko
module: BitByteData
module_version: 1.0.0-dev
copyright: '© 2017 Timofey Solomko'
readme: README.md
github_url: https://github.com/tsolomko/BitByteData
github_file_prefix: https://github.com/tsolomko/BitByteData/tree/develop
theme: fullwidth
