# Run: sourcekitten doc --spm-module BitByteData > docs.json
sourcekitten_sourcefile: docs.json
clean: true
author: Timofey Solomko
module: BitByteData
module_version: 1.0.0-test.2
copyright: '© 2018 Timofey Solomko'
readme: README.md
github_url: https://github.com/tsolomko/BitByteData
github_file_prefix: https://github.com/tsolomko/BitByteData/tree/develop
theme: fullwidth

custom_categories:
    - name: Reading bytes
      children:
      - ByteReader
    - name: Reading bits (and bytes)
      children:
      - BitReader
      - LsbBitReader
      - MsbBitReader
    - name: Writing bits (and bytes)
      children:
      - BitWriter
      - LsbBitWriter
      - MsbBitWriter
